# Generated by Django 5.1.4 on 2025-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='person_pics/'),
        ),
    ]
