# Generated by Django 5.1.4 on 2025-02-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_department_person_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('upload_picture', 'Can upload and change person picture'), ('assign_to_department', 'Can assign person to department'))},
        ),
    ]
